### ISSUE TITLE
Could you provide some brief documentation on running the package? 

### ISSUE THREAD

**Issue by ghostbeagle** [jychp/apipyfy#1]
Hi, could you post some details on how to run this package?  

I've tried to run from some of the individual directories in apipyfy/, for instance domain big data, but I consistently get this error 

```
`Traceback (most recent call last):
  File "domainbigdata/api.py", line 6, in <module>
    from apipyfy.base import BaseAPI
ModuleNotFoundError: No module named 'apipyfy'`
```

I also tried to append a couple filepaths to the beginning of the program using sys.path.append(<filepath>), but unfortunately that also did not work. 

 ```
 File "api.py", line 9, in <module>
    from api.base import BaseAPI
  File "/Users/Username/Apipipfy/apipyfy/apipyfy/domainbigdata/api.py", line 9, in <module>
    from api.base import BaseAPI
ModuleNotFoundError: No module named 'api.base'; 'api' is not a package
```

This looks like a great package and I'd love to use it. I'm just unsure how to get it up and running. Thanks!

**Comment by jychp** [comment]
I just add a PIP install script, so you can:

```cmd
git clone https://github.com/jychp/apipyfy
cd apipyfy
pip3 install .
```

Then you can use in your scripts:

```python3
from apipyfy import NeededNameAPI

api = NeededNameAPI()
```

**Comment by jychp** [comment]
or simply: 
> pip3 install git+https://github.com/jychp/apipyfy
